[DIRECTORIES]
BaseDirectory = relatedObjects
SecondDirectory = Yearbooks
; Name the folder containing all files created after running the script
ContentDirectory = 1996

[INFORMATION]
Title = 1996 Yearbook
Pages = 186
Height = 3420
Width = 2553
Base = yearbook_1996_000